#!/usr/bin/env bash
#
# If $GIT_BRANCH_PREFIX is set, requires confirmation for pushes to remote
# branches whose names don't begin with that prefix.

# parse out the remote ref name
# args are (local_ref local_sha remote_ref remote_sha)
read -a args
ref=${args[2]}
ref_name=${ref##*/}

if [[ ! -z "$GIT_BRANCH_PREFIX" ]] && [[ ! -z "$ref_name" ]]; then
    if [[ "$ref_name" != $GIT_BRANCH_PREFIX* ]]; then
        exec ~/.config/git/hooks/prompt "Push to $ref that doesn't begin with $GIT_BRANCH_PREFIX?"
        printf "Pushing to $ref.\n"
    fi
fi

exit 0
