#!/bin/bash

power_off="S shutdown"
reboot="R reboot"
lock="L lock"
log_out="G logout"

options="$power_off\n$reboot\n$lock\n$log_out"
selection="$(echo -e "$options" | rofi -dmenu -selected-row 2)"
case $selection in
    $power_off)
        systemctl poweroff
        ;;
    $reboot)
        systemctl reboot
        ;;
    $lock)
        xset s activate
        ;;
    $log_out)
        i3-msg exit
        ;;
esac
