#!/bin/bash

power_off="S shutdown"
reboot="R reboot"
lock="L lock"
log_out="G logout"

options="$power_off\n$reboot\n$lock\n$log_out"
selection="$(echo -e "$options" | rofi -dmenu -selected-row 2)"
case $selection in
    $power_off)
        systemctl poweroff
        ;;
    $reboot)
        systemctl reboot
        ;;
    $lock)
        xset s activate
        ;;
    $log_out)
        # close all open windows
        WIN_IDs=$(wmctrl -l | awk '$3 != "N/A" {print $1}')
        for i in $WIN_IDs; do wmctrl -ic "$i"; done
        # logout from the current session
        session=$(loginctl session-status | awk 'NR==1{print $1}')
        loginctl terminate-session "$session"
        ;;
esac
