# If HHKB: remap for 65% ergonomics and then configure caps lock to be ctrl on hold + esc on tap
- JOB: intercept -g $DEVNODE | caps2esc -m 2 | dual-function-keys -c /home/rhys/.config/interception/dual-function-keys.yaml | uinput -d $DEVNODE
  DEVICE:
    EVENTS:
      EV_KEY: [[KEY_ESC]]
    NAME: "Topre Corporation HHKB Professional"

# Else: only remap caps lock
- JOB: intercept -g $DEVNODE | caps2esc -m 1 | uinput -d $DEVNODE
  DEVICE:
    EVENTS:
      EV_KEY: [[KEY_ESC]]
    LINK: .*-event-kbd

