#!/usr/bin/env bash
# rejects commits that don't match the conventional commit format
# see: www.conventionalcommits.org

commit_types=(
    "build"
    "ci"
    "docs"
    "feat"
    "fix"
    "perf"
    "refactor"
    "revert"
    "style"
    "test"
)

for t in "${commit_types[@]}"; do
    type_alternatives="${type_alternatives:+$type_alternatives}\|$t"
done

type_regex="\($type_alternatives\)"
scope_regex="\((.\+)\)\?"
commit_regex="^$type_regex$scope_regex!\?: .*$"

# check if the commit subject conforms to the regex
commit_subject=$(head -n1 $1)
regex_match=$(echo "$commit_subject" | grep "$commit_regex")

test ! -z "$regex_match" || {
    printf "$commit_subject\ndoesn't match commit format\n$commit_regex\n"
    exit 1
}

if ((${#regex_match} > 50)); then
    printf "$commit_subject\nhas a title longer than 50 characters\n"
    exit 1
fi

exit 0
