#!/usr/bin/env bash
# rejects commits that don't match the conventional commit format
# see: www.conventionalcommits.org

# build a regex for the commit message
commit_types=(
    "build"
    "ci"
    "docs"
    "feat"
    "fix"
    "perf"
    "refactor"
    "revert"
    "style"
    "test"
)

for t in "${commit_types[@]}"; do
    type_alternatives="${type_alternatives:+$type_alternatives}\|$t"
done

type_regex="\($type_alternatives\)"
scope_regex="\((.\+)\)\?"
commit_regex="^$type_regex$scope_regex!\?: .*$"

# check if the commit subject conforms to the regex
commit_subject=$(head -n1 $1)
regex_match=$(echo "$commit_subject" | grep "$commit_regex")

# exit if the commit message doesn't match the regex
test ! -z "$regex_match" || {
    exec ~/bin/prompt "[$commit_subject] doesn't match commit format. Continue?"
}

# exit if the commit message is too long
if ((${#regex_match} > 50)); then
    exec ~/bin/prompt "[$commit_subject] has a title longer than 50 characters. Continue?"
fi

exit 0
