#!/usr/bin/env bash
# confirms pushes to remote branches without the whitelisted prefix

# parse out the remote ref name
# args are (local_ref local_sha remote_ref remote_sha)
read -a args
ref=${args[2]}
ref_name=${ref##*/}

# whitelisted branch prefix
prefix="ro-"

if [[ "$ref_name" != $prefix* ]]; then
    # assign stdin to the keyboard, prompt the user, and close stdin
    exec < /dev/tty
    read -p "Push to $ref that doesn't begin with $prefix? (y/n): " push
    exec <&-

    if [[ "$push" == y* ]]; then
        printf "Pushing to $ref.\n"
    else
        printf "Not pushing to $ref.\n"
        exit 1
    fi
fi

exit 0
